DROP TABLE p9ocr.Patient;

CREATE TABLE p9ocr.Patient (
  PATIENT_ID INT NOT NULL AUTO_INCREMENT,
  LAST_NAME VARCHAR(50) NOT NULL,
  FIRST_NAME VARCHAR(50) NOT NULL,
  FAMILLY VARCHAR(50) NOT NULL,
  GIVEN VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  SEX VARCHAR(10) NOT NULL,
  BIRTH_DATE DATE,
  CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (PATIENT_ID)
)
;

insert into p9ocr.Patient(LAST_NAME, FIRST_NAME, FAMILLY, GIVEN, ADDRESS, SEX, BIRTH_DATE)
    values("DUPOND", "Alain", "TestNone", "Test", "12 rue des olivier 78000 Versailles", "F", STR_TO_DATE('24-09-1995', '%d-%m-%Y'))
;
insert into p9ocr.Patient(LAST_NAME, FIRST_NAME, FAMILLY, GIVEN, ADDRESS, SEX, BIRTH_DATE)
    values("DUPONT", "Alain", "TestNone", "Test", "12 rue des olivier 78000 Versailles", "F", STR_TO_DATE('24-09-1995', '%d-%m-%Y'))
;

commit;