DROP TABLE p9ocr.Patient;

CREATE TABLE p9ocr.Patient (
  PATIENT_ID INT NOT NULL AUTO_INCREMENT,
  FAMILLY VARCHAR(50) NOT NULL,
  GIVEN VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  PHONE VARCHAR(30) NOT NULL,
  SEX VARCHAR(10) NOT NULL,
  BIRTH_DATE DATE,
  CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (PATIENT_ID)
)
;

insert into p9ocr.Patient(FAMILLY, GIVEN, ADDRESS, SEX, BIRTH_DATE, PHONE)
    values("DUPOND", "Alain", "12 rue des olivier 78000 Versailles", "F", STR_TO_DATE('24-09-1995', '%d-%m-%Y'),'+33 123456789')
;
insert into p9ocr.Patient(FAMILLY, GIVEN, ADDRESS, SEX, BIRTH_DATE, PHONE)
    values("DUPONT", "Alain", "12 rue des olivier 78000 Versailles", "F", STR_TO_DATE('24-09-1995', '%d-%m-%Y'),'+33 123456780')
;

commit;